# GitHub Pages Remote Theme Config
plugins:
  - jekyll-remote-theme

remote_theme: kitian616/jekyll-TeXt-theme

# TeXt Theme Settings
text_skin: dark

# Site Details
title: Dwilsy's Page
description: WRT4LYFE
author: Dom

mathjax: true
