# GitHub Pages Remote Theme Config
plugins:
  - jekyll-remote-theme

remote_theme: kitian616/jekyll-TeXt-theme

# Site Details
author: Dom
description: WRT4LYFE

# TeXt Theme Settings Structure
site:
  skin: dark

site_text:
  title: Dwilsy's Page
  subtitle: Welcome to my blog!

mathjax: true
